id: PB35EC33B
initial_creation_type: ocr
source_metadata:
  volumes:
    99f115cb9573421d9dcbe723b9372c1b:
      base_file: v083.txt
      image_group_id: I1PD95928
      title: བསྟན་བཅོས་ཚིགས་སུ་བཅད་པ་བསྡུས་པ།
      total_pages: 1296
      volume_number: 83
