id: DC0E21B7D
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2021-12-31T07:05:20+00:00'
last_modified: '2022-05-29T08:52:54.203007+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/a7eec5e12ddce18d0ed1dbb732a42cf48f94dd09/openpecha/formatters/hfml.py
source_metadata:
  base:
    4a92:
      image_group_id: I1PD95928
      title: བསྟན་བཅོས་ཚིགས་སུ་བཅད་པ་བསྡུས་པ།
      total_pages: 1296
      order: 83
      base_file: 4a92.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
